backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;

use common\models\Purpose;
use common\models\Project;
use common\models\User;
use common\models\Login;
use common\models\SignUpForm;

class SiteController extends Controller
{

	public function behaviors() {
		return [
			'access' => ['class' => AccessControl::className(),
			'rules' => [
				[
					'actions' => [
						'signup',
						'login',
						'error'
					],
					'allow' => true,
				],
				[
					'actions' => [
						'logout',
						'index',
						'add-project',
						'update-project',
						'delete-project',
						'project',
						'down',
						'create',
						'update',
						'delete',
					],
					'allow' => true,
					'roles' => ['@'],
				],
			],
		],
	];
}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex() {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = Project::find()->orderBy(['date' => SORT_ASC]);
		return $this->render('index', [
			'model' => $model
		]);
	}

	public function actionProject($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();
		$project = Project::find()->where(['id' => $id])->one();
		$model = Purpose::find()->where(['project_id' => $id]);
		$done = Purpose::find()->where(['project_id' => $id, 'status' => 1])->count();
		$all = $model->count();
		return $this->render('project', [
			'project' => $project,
			'model' => $model,
			'done' => $done,
			'all' => $all,
		]);
	}

	public function actionCreate($id) {

		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Purpose();

		if (Yii::$app->request->isPost) {
			$model->name = Yii::$app->request->post()['Purpose']['name'];
			$model->desc = Yii::$app->request->post()['Purpose']['desc'];
			$model->status = Yii::$app->request->post()['Purpose']['status'];
			$model->project_id = $id;
			$model->date = date('Y-m-d');
			$model->save();
			return $this->redirect(['/site/project', 'id' => $id]);
		}

		return $this->render('create', [
			'model' => $model,
			'statuses' => Purpose::allStatuses(),
			'projects' => $this->getProjects(),
		]);
	}

	public function actionUpdate($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Purpose::findIdentity($id);

		if (Yii::$app->request->isPost) {
			$model->name = Yii::$app->request->post()['Purpose']['name'];
			$model->desc = Yii::$app->request->post()['Purpose']['desc'];
			$model->status = Yii::$app->request->post()['Purpose']['status'];
			$model->save();
			return $this->redirect(['/site/project', 'id' => $model->project_id]);
		}

		return $this->render('create', [
			'model' => $model,
			'statuses' => Purpose::allStatuses(),
			'projects' => $this->getProjects(),
		]);
	}

	public function actionDelete($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Purpose::findIdentity($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionAddProject() {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Project();

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Project']['title'];
			$model->desc = Yii::$app->request->post()['Project']['desc'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-project', [
			'model' => $model,
		]);
	}

	public function actionUpdateProject($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = Project::findOne($id);

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Project']['title'];
			$model->desc = Yii::$app->request->post()['Project']['desc'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-project', [
			'model' => $model,
		]);
	}

	public function actionDeleteProject($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Project::findOne($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionSignup() {

		$this->layout = 'login';

		$model = new SignUpForm();

		if(isset($_POST['SignUpForm'])) {
			$model->attributes = Yii::$app->request->post('SignUpForm');
			if($model->validate() && $model->signup()) {
				return $this->redirect(['login']);
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}

	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		
		$this->layout = 'login';

		$model = new Login();

		if( Yii::$app->request->post('Login')) {
			$model->attributes = Yii::$app->request->post('Login');
			$user = $model->getUser();
			if($model->validate()) {
				if($user->isAdmin($user['id'])) {
					Yii::$app->user->login($user);
					return $this->goHome();
				}
			}
		}

		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout() {
		Yii::$app->user->logout();
		return $this->goHome();
	}

	public function getProjects() {
		$projects = [];
		$all_projects = Project::find()->all();

		for ($i=0; $i < count($all_projects); $i++) $projects[$all_projects[$i]->id] = $all_projects[$i]->title;

		return $projects;
	}

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class SiteController extends Controller {

	public function behaviors() {
		return [
		];
	}

	public function actions() {
		return [
		];
	}

	public function actionIndex() {
		return $this->redirect(['admin/']);
	}


}

backend/views/site/add-project.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use dosamigos\datetimepicker\DateTimePicker;

$this->title = Yii::t('app', 'Новый проект');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"></div>
		<div class="panel-body">

			<div class="link-update">
				<?php $form = ActiveForm::begin(); ?>

				<?= $form->field($model, 'title')->textInput() ?>
				<?= $form->field($model, 'desc')->textArea() ?>

				<div class="form-group center">
					<?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/create.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use dosamigos\datetimepicker\DateTimePicker;

$this->title = Yii::t('app', 'Новая запись');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"></div>
		<div class="panel-body">

			<div class="link-update">
				<?php $form = ActiveForm::begin(); ?>

				<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
				<?= $form->field($model, 'desc')->textArea() ?>
				<?= $form->field($model, 'status')->dropDownList($statuses) ?>

				<div class="form-group center">
					<?= Html::submitButton(Yii::t('app', 'Добавить'), ['class' =>  'btn btn-success']) ?>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\models\User;

$this->title = Yii::t('app', 'Новые проекты');
$this->params['breadcrumbs'][] = $this->title;

$dataProvider = new ActiveDataProvider([
	'query' => $model,
	'pagination' => [
	 'pageSize' => 20,
	],
]);

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"><?= $this->title ?></div>
		<div class="panel-body">

<div class="contact-index">
		<?= Html::a(Yii::t('app','Добавить'), Url::base() . '/site/create') ?>
	<div class="fa-br"></div>
	<br>
	<?php
	echo GridView::widget([
		'dataProvider' => $dataProvider,
		'layout' => "{items}\n{pager}",
		'columns' => [
			'title',
			[
				'label' => 'Описание',
				'attribute' => 'desc',
				'value' => function($data){
					return substr($data->desc, 0, 100) . (strlen($data->desc) > 100 ? '...' : '');
				}
			],
			[
				'class' => 'yii\grid\ActionColumn',
				'header'=>'Действия', 
				'headerOptions' => ['width' => '80'],
				'template' => '{update} {delete}',
				'buttons' => [
					'update' => function ($url, $model) {
						return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['site/update-project', 'id'=>$model->id ], [
							'title' => Yii::t('app', 'lead-update'),
						]);
					},
					'delete' => function ($url, $model) {
						return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['site/delete-project', 'id'=>$model->id ], [
							'title' => Yii::t('app', 'lead-delete'),
						]);
					}

				],
			],
		],
	]);
	?>

</div>

		</div>
	</div>
</div>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
	<div class="row">
		<div class="login-box">
			<div class="col-md-12 box box-radius">
			<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

				<?= $form->field($model, 'email', ['template' => '
						<div class="col-sm-12" style="margin-top:15px;">
							<div class="input-group col-sm-12">
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-user"></span>
								</span>
								{input}
							</div>{error}{hint}
						</div>'])->textInput(['autofocus' => true])
								->input('text', ['placeholder'=>'email']) ?>

				<?= $form->field($model, 'password', ['template' => '
						<div class="col-sm-12" style="margin-top:15px;">
							<div class="input-group col-sm-12">
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-lock"></span>
								</span>
								{input}
							</div>{error}{hint}
						</div>'])->passwordInput()
								->input('password', ['placeholder'=>'Password'])?>

				<div class="form-group">
					<?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
					<hr>
					<?= Html::a('Регистрация', ['/site/signup'],['class' => 'btn']) ?>
				</div>

			<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/project.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\models\User;

$this->title = Yii::t('app', 'Цели');
$this->params['breadcrumbs'][] = $this->title;

$dataProvider = new ActiveDataProvider([
	'query' => $model,
	'pagination' => [
	 'pageSize' => 20,
	],
]);

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"><?= $this->title ?></div>
		<div class="panel-body">
			<div class="progress-group">
				<span class="progress-text">Готово целей</span>
				<span class="progress-number"><b><?= $done ?></b>/<?= $all ?></span>

				<div class="progress sm">
					<div class="progress-bar progress-bar-aqua" style="width:<?= ($all == 0 ? 0 : floor($done/$all * 100)) . '%'; ?>"></div>
				</div>
			</div>
			<div class="contact-index">
					<?= Html::a(Yii::t('app','Добавить цель'), ['/site/create', 'id' => $_GET['id']]) ?>
				<div class="fa-br"></div>
				<br>
				<?php
				echo GridView::widget([
					'dataProvider' => $dataProvider,
					'layout' => "{items}\n{pager}",
					'columns' => [
						'name',
						[
							'label' => 'Описание',
							'attribute' => 'desc',
							'value' => function($data){
								return substr($data->desc, 0, 100) . (strlen($data->desc) > 100 ? '...' : '');
							}
						],
						[
							'label' => 'Статус',
							'attribute' => 'status',
							'value' => function($data){
								return $data->getStatus();
							}
						],
						[
							'class' => 'yii\grid\ActionColumn',
							'header'=>'Действия', 
							'headerOptions' => ['width' => '80'],
							'template' => '{update} {delete}',
						],
					],
				]);
				?>

			</div>

		</div>
	</div>
</div>

backend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
	<div class="row">
		<div class="login-box">
			<div class="col-md-12 box box-radius">
			<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

				<?= $form->field($model, 'username', ['template' => '
						<div class="col-sm-12" style="margin-top:15px;">
							<div class="input-group col-sm-12">
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-user"></span>
								</span>
								{input}
							</div>{error}{hint}
						</div>'])->textInput(['autofocus' => true])
								->input('text', ['placeholder'=>'Логин']) ?>

				<?= $form->field($model, 'email', ['template' => '
						<div class="col-sm-12" style="margin-top:15px;">
							<div class="input-group col-sm-12">
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-user"></span>
								</span>
								{input}
							</div>{error}{hint}
						</div>'])->textInput()
								->input('text', ['placeholder'=>'email']) ?>

				<?= $form->field($model, 'password', ['template' => '
						<div class="col-sm-12" style="margin-top:15px;">
							<div class="input-group col-sm-12">
								<span class="input-group-addon">
									<span class="glyphicon glyphicon-lock"></span>
								</span>
								{input}
							</div>{error}{hint}
						</div>'])->passwordInput()
								->input('password', ['placeholder'=>'Пароль'])?>

				<div class="form-group">
					<?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
					<hr>
					<?= Html::a('Войти', ['/site/login'],['class' => 'btn']) ?>
				</div>

			<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/update.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use dosamigos\datetimepicker\DateTimePicker;

$this->title = Yii::t('app', 'Кандидаты');

$status = '';
?>
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading"><?= $model->title ?></div>
        <div class="panel-body">

<?php



$this->title = Yii::t('app', 'Update');

$this->params['breadcrumbs'][] = ['label' => 'Записи'];
$this->params['breadcrumbs'][] = ['label' => $model->title];
?>
<div class="link-update">

	<?php $form = ActiveForm::begin(); ?>

	<?= $form->field($model, 'title')->textInput(['placeholder' => '']) ?>
	<?= $form->field($model, 'desc')->textArea(['placeholder' => '']) ?>
	<?= $form->field($model, 'status')->dropDownList([
		'1' => 'Активен',
		'0' => 'Завершен',
	]) ?>


	<div class="form-group center">
		<?= ''// Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
		<?= Html::submitButton(Yii::t('app', 'Update'), ['class' =>  'btn btn-success']) ?>
	</div>
	<?php ActiveForm::end(); ?>


</div>

        </div>
    </div>
</div>